env:
  es2018: true
  node: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - '**/cdk.out/'
rules:
  import/extensions: [error, never]  # import文の拡張子を禁止する
  import/prefer-default-export: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
